//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Messages struct {
	MessageID string
	ServerID  string `sql:"primary_key"`
	Activity  string `sql:"primary_key"`
	Position  int32
}
