//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Servers struct {
	ID                string `sql:"primary_key"`
	ServerName        string
	ChannelName       string
	Schedule          string
	ShouldEditMessage bool
	IsEnabled         bool
}
