//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Users struct {
	OsrsUsernameKey string `sql:"primary_key"`
	ServerID        string `sql:"primary_key"`
	OsrsUsername    string
	OsrsAccountType string
	DiscordUsername string
	DiscordUserID   string
}
