//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Messages = newMessagesTable("", "messages", "")

type messagesTable struct {
	sqlite.Table

	// Columns
	MessageID sqlite.ColumnString
	ServerID  sqlite.ColumnString
	Activity  sqlite.ColumnString
	Position  sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MessagesTable struct {
	messagesTable

	EXCLUDED messagesTable
}

// AS creates new MessagesTable with assigned alias
func (a MessagesTable) AS(alias string) *MessagesTable {
	return newMessagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MessagesTable with assigned schema name
func (a MessagesTable) FromSchema(schemaName string) *MessagesTable {
	return newMessagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MessagesTable with assigned table prefix
func (a MessagesTable) WithPrefix(prefix string) *MessagesTable {
	return newMessagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MessagesTable with assigned table suffix
func (a MessagesTable) WithSuffix(suffix string) *MessagesTable {
	return newMessagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMessagesTable(schemaName, tableName, alias string) *MessagesTable {
	return &MessagesTable{
		messagesTable: newMessagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newMessagesTableImpl("", "excluded", ""),
	}
}

func newMessagesTableImpl(schemaName, tableName, alias string) messagesTable {
	var (
		MessageIDColumn = sqlite.StringColumn("message_id")
		ServerIDColumn  = sqlite.StringColumn("server_id")
		ActivityColumn  = sqlite.StringColumn("activity")
		PositionColumn  = sqlite.IntegerColumn("position")
		allColumns      = sqlite.ColumnList{MessageIDColumn, ServerIDColumn, ActivityColumn, PositionColumn}
		mutableColumns  = sqlite.ColumnList{MessageIDColumn, PositionColumn}
		defaultColumns  = sqlite.ColumnList{MessageIDColumn, ServerIDColumn, ActivityColumn, PositionColumn}
	)

	return messagesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		MessageID: MessageIDColumn,
		ServerID:  ServerIDColumn,
		Activity:  ActivityColumn,
		Position:  PositionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
